### ISSUE TITLE
MFTF 2.5.x compatibility

### ISSUE THREAD

**Issue by thomas-kl1** [M2Coach/MFTF-MailHog-Wrapper#4]
Have you any plan to port the compatibility of MFTF MailHog Wrapper to MFTF >2.5?

**Comment by lbajsarowicz** [comment]
Hi @thomas-kl1 I just verified the compatibility.
Looks like everything works properly with 2.5 too.

I'm going to update `composer.json` file in minutes.

**Comment by lbajsarowicz** [comment]
Solved.

**Comment by thomas-kl1** [comment]
Thank you!
